[package]
name = "bba"
version = "0.1.0"
authors = ["Nick Dolan <nicholas.dolan1@gmail.com>, Grace Chenevert, Cameron Otts, Aaron Dentro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
chrono = "0.4"
diesel = { version = "1.0.0", default_features = false, features = ["chrono", "r2d2", "postgres"] }
dotenv = "0.9.0"
env_logger = "0.6"
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.14"
