apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
        name: actixweb
    spec:
        selector:
            app: actixweb
        ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
          nodePort: 31317
        type: NodePort
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: actixweb
    spec:
        replicas: 1
        strategy:
            type: RollingUpdate
            rollingUpdate:
                maxSurge: 50%
        selector: 
            matchLabels:
                app: actixweb
        template:
            metadata:
                labels:
                    app: actixweb
            spec:
                volumes: []
                containers:
                    - name: main
                      image: cotts/biggestblackestapi_actixweb
                      imagePullPolicy: Always
                      ports:
                          - containerPort: 8080
                      volumeMounts: []
                      env:
                        - name: DATABASE_URL
                          value: postgres://bba:MySeCrEtPaSsWoRd@192.168.64.6:30000/bba
  - apiVersion: v1
    kind: Service
    metadata:
        name: postgres
    spec:
        selector:
            app: postgres
        ports:
            - port: 5432
              protocol: TCP
              targetPort: 5432
              nodePort: 30000
        type: NodePort
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: postgres
    spec:
        strategy:
            type: RollingUpdate
            rollingUpdate:
                maxSurge: 50%
        selector: 
            matchLabels:
                app: postgres
        template:
            metadata:
                labels:
                    app: postgres
            spec:
                volumes: []
                containers:
                    - name: main
                      image: cotts/biggestblackestapi_postgresdb
                      imagePullPolicy: Always
                      ports:
                          - containerPort: 5432
                      volumeMounts: []
                      env:
                        - name: POSTGRES_PASSWORD
                          value: MySeCrEtPaSsWoRd
                        - name: POSTGRES_USER
                          value: bba