// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package biggestblackestapi

type Card struct {
	ID      string `json:"Id"`
	IsBlack bool   `json:"IsBlack"`
	Set     *Set   `json:"Set"`
	Text    string `json:"Text"`
}

type Set struct {
	ID   string `json:"Id"`
	Name string `json:"Name"`
}
